# ~/.tmux.conf

set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# STATUS BAR STYLING

## 'variables' for foreground and background
set -g @fg "#141414" #F87C63 #F54927 #1C2433
set -g @bg "#bb96cb"

## Status bar
set -g status-style "bg=#{@bg},fg=#{@fg}"

## Active window
set -g window-status-current-style "bg=#{@fg},fg=#{@bg}"

## Active window (with special style, no asterisk)
set -g window-status-current-format " #I:#W "

# ...

unbind C-b
set -g prefix C-a
bind C-a send-prefix
